server:
  port: ${PORT}

spring:
  application:
    name: rsp-talentcore-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://RSP-TALENTCORE-AUTH-SERVICE
              predicates:
                - Path=/api/users/**

            - id: core-service
              uri: lb://RSP-TALENTCORE-CORE-SERVICE
              predicates:
                - Path=/api/resources/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allow-credentials: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

logging:
  level:
    root: INFO
    org.springframework: WARN