import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { KpiCardComponent } from './kpi-card.component';
import { AuthService } from '../../core/auth/auth.service';

type DashboardMetric = {
  title: string;
  value: string;
  subtext: string;
  icon: string;
  trend: string;
  trendType: 'positive' | 'negative';
};

@Component({
  standalone: true,
  selector: 'feature-dashboard',
  imports: [CommonModule, RouterModule, KpiCardComponent],
  template: `
    <section class="dashboard-shell">
      <div class="dashboard-header">
        <div>
          <p class="eyebrow">Welcome back</p>
          <h1>{{ displayName }}</h1>
          <p class="dashboard-copy">Your enterprise workspace is up to date. Review your KPI insights, track activity, and manage high-priority items.</p>
        </div>
      </div>

      <div class="kpi-grid">
        <app-kpi-card
          *ngFor="let metric of metrics"
          [title]="metric.title"
          [value]="metric.value"
          [subtext]="metric.subtext"
          [icon]="metric.icon"
          [trend]="metric.trend"
          [trendType]="metric.trendType">
        </app-kpi-card>
      </div>

      <div class="dashboard-panels">
        <section class="panel welcome-panel">
          <div class="panel-head">
            <div>
              <p class="panel-label">Quick Summary</p>
              <h2>Platform overview</h2>
            </div>
            <span class="status-chip">Healthy</span>
          </div>
          <div class="panel-details">
            <div>
              <span class="panel-value">24</span>
              <span class="panel-caption">Active projects this quarter</span>
            </div>
            <div>
              <span class="panel-value">76%</span>
              <span class="panel-caption">Resource utilization</span>
            </div>
            <div>
              <span class="panel-value">4.9</span>
              <span class="panel-caption">Net satisfaction score</span>
            </div>
          </div>
        </section>

        <section class="panel activity-panel">
          <div class="panel-head">
            <div>
              <p class="panel-label">Recent activity</p>
              <h2>System updates</h2>
            </div>
            <button class="ghost-button">View all</button>
          </div>
          <ul class="activity-list">
            <li>
              <span class="dot success"></span>
              New user onboarding completed for <strong>EMP-1124</strong>
            </li>
            <li>
              <span class="dot warning"></span>
              Project <strong>Atlas Revamp</strong> moved to execution phase
            </li>
            <li>
              <span class="dot accent"></span>
              4 reports generated by the executive team
            </li>
          </ul>
        </section>
      </div>
    </section>
  `,
  styles: [
    `
      .dashboard-shell {
        display: grid;
        gap: 1rem;
        padding: 1rem 1.5rem 1.5rem;
        max-width: 1320px;
        margin: 0 auto;
      }

      .dashboard-header {
        display: flex;
        justify-content: space-between;
        gap: 1rem;
        align-items: center;
        background: linear-gradient(180deg, rgba(201, 32, 47, 0.08), rgba(255, 255, 255, 0.8));
        border: 1px solid rgba(201, 32, 47, 0.12);
        border-radius: 16px;
        padding: 0.9rem 1.1rem;
        box-shadow: var(--shadow-soft);
      }

      .eyebrow {
        margin: 0 0 0.3rem;
        font-size: 0.76rem;
        letter-spacing: 0.15em;
        text-transform: uppercase;
        color: #b9242f;
      }

      .dashboard-header h1 {
        margin: 0;
        font-size: clamp(1.65rem, 2vw, 2.25rem);
        line-height: 1.1;
      }

      .dashboard-copy {
        margin: 0.35rem 0 0;
        max-width: 640px;
        color: var(--tc-grey);
        line-height: 1.45;
      }

      .dashboard-actions {
        display: flex;
        gap: 0.85rem;
        flex-wrap: wrap;
      }

      .primary-button,
      .secondary-button,
      .ghost-button {
        border: none;
        border-radius: 999px;
        cursor: pointer;
        font-weight: 700;
      }

      .primary-button {
        background: var(--tc-red);
        color: white;
        padding: 0.88rem 1.4rem;
      }

      .secondary-button {
        background: white;
        color: var(--tc-slate);
        border: 1px solid rgba(23, 33, 43, 0.12);
        padding: 0.88rem 1.4rem;
      }

      .kpi-grid {
        display: grid;
        grid-template-columns: repeat(4, minmax(220px, 1fr));
        gap: 1rem;
      }

      .dashboard-panels {
        display: grid;
        grid-template-columns: 1.3fr 0.9fr;
        gap: 1rem;
      }

      .panel {
        background: white;
        border-radius: 18px;
        padding: 1.15rem;
        box-shadow: var(--shadow-soft);
      }

      .panel-head {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        margin-bottom: 1rem;
      }

      .panel-label {
        margin: 0;
        font-size: 0.82rem;
        letter-spacing: 0.18em;
        text-transform: uppercase;
        color: var(--tc-red);
      }

      .panel h2 {
        margin: 0.4rem 0 0;
        font-size: 1.35rem;
      }

      .status-chip {
        display: inline-flex;
        align-items: center;
        gap: 0.35rem;
        padding: 0.55rem 0.9rem;
        border-radius: 999px;
        background: #f9eef0;
        color: #aa1f2b;
        font-weight: 700;
        font-size: 0.85rem;
      }

      .panel-details {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 1rem;
      }

      .panel-value {
        display: block;
        font-size: 2rem;
        font-weight: 700;
      }

      .panel-caption {
        color: var(--tc-grey);
        margin-top: 0.4rem;
      }

      .activity-list {
        list-style: none;
        margin: 0;
        padding: 0;
        display: grid;
        gap: 0.95rem;
      }

      .activity-list li {
        display: flex;
        align-items: center;
        gap: 0.8rem;
        padding: 0.8rem 0.9rem;
        border-radius: 14px;
        background: #fbf7f7;
        color: var(--tc-slate);
      }

      .dot {
        width: 12px;
        height: 12px;
        border-radius: 999px;
        flex-shrink: 0;
      }

      .dot.success { background: #128a3d; }
      .dot.warning { background: #f6b345; }
      .dot.accent { background: #c9202f; }

      .ghost-button {
        background: transparent;
        color: var(--tc-red);
        border: 1px solid rgba(201, 32, 47, 0.16);
        padding: 0.7rem 1rem;
      }

      @media (max-width: 1080px) {
        .kpi-grid {
          grid-template-columns: repeat(2, minmax(220px, 1fr));
        }

        .dashboard-panels {
          grid-template-columns: 1fr;
        }
      }

      @media (max-width: 720px) {
        .dashboard-shell {
          padding: 1rem;
        }

        .dashboard-header {
          flex-direction: column;
          align-items: stretch;
        }

        .dashboard-actions {
          justify-content: stretch;
        }

        .dashboard-actions button {
          width: 100%;
        }
      }
    `
  ]
})
export class DashboardComponent {
  metrics: DashboardMetric[] = [
    { title: 'Total Users', value: '1,248', subtext: 'Corporate and external accounts', icon: 'groups', trend: '+6.2%', trendType: 'positive' },
    { title: 'Active Projects', value: '24', subtext: 'Projects running this quarter', icon: 'workspace_premium', trend: '+12%', trendType: 'positive' },
    { title: 'Resource Allocations', value: '76%', subtext: 'Utilization rate across teams', icon: 'assignment_ind', trend: '+3.8%', trendType: 'positive' },
    { title: 'Open Reports', value: '8', subtext: 'Pending review and approval', icon: 'insights', trend: '-1.4%', trendType: 'negative' }
  ];

  constructor(private auth: AuthService) {}

  get displayName(): string {
    const profile = this.auth.currentUser();
    const name = [profile?.firstName, profile?.lastName].filter(Boolean).join(' ');
    if (name) return name;
    return 'TalentCore User';
  }
}
