# Application
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/talentcore_core
spring.datasource.username=talentcore_user
spring.datasource.password=root

# JWT
jwt.secret=TalentCoreSecretKeyForJWTAuthenticationAndAuthorization2026DevelopmentEnvironmentOnly