# Application
spring.application.name=rsp-talentcore-core-service
server.port=${PORT}

debug=false

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

# Logging
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.com.rsp.talentcore=INFO
logging.level.com.nexora.rsp.talentcore=INFO
logging.level.org.flywaydb=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=WARN

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000